### ISSUE TITLE
TransportBuilder throws fatal error when sending a mail via flowmailer using Magento 2.3.3

### ISSUE THREAD

**Issue by timsassen** [flowmailer/m2connector#3]
A fatal error is thrown when sending the order confirm mail via the FlowMailer connector:

> Fatal error: Uncaught Error: Call to undefined method Magento\Framework\Mail\EmailMessage::setTemplateVars() in /var/www/sbk/2-3-3-flowmailer-check/vendor/flowmailer/m2connector/Model/Mail/Template/TransportBuilder.php:111 
Stack trace: #0 /var/www/sbk/2-3-3-flowmailer-check/vendor/magento/framework/Mail/Template/TransportBuilder.php(337): Flowmailer\M2Connector\Model\Mail\Template\TransportBuilder->prepareMessage() 
#1 /var/www/sbk/2-3-3-flowmailer-check/generated/code/Flowmailer/M2Connector/Model/Mail/Template/TransportBuilder/Interceptor.php(154): Magento\Framework\Mail\Template\TransportBuilder->getTransport() 
#2 /var/www/sbk/2-3-3-flowmailer-check/vendor/magento/module-customer/Model/EmailNotification.php(272): Flowmailer\M2Connector\Model\Mail\Template\TransportBuilder\Interceptor->getTransport() 
#3 /var/www/sbk/2-3-3-flowmailer-check/vendor/magento/module-customer/Model/EmailNotification.php(398): Magento\Customer\Model\EmailNotification->sendEmailTemplate(Object(Magento\Customer\Model\Data\Customer), 'customer/creat in /var/www/sbk/2-3-3-flowmailer-check/vendor/flowmailer/m2connector/Model/Mail/Template/TransportBuilder.php on line 111

Steps to reproduce:

1. Install a fresh instance of Magento 2.3.3
2. Install the latest flowmailer/m2connector package and configure it.
3. Add a product via the admin interface.
4. Add a order via the admin interface.
5. The product is not added and the exception mentioned above is thrown

**Comment by flowmailer-richard** [comment]
Thanks for reporting, they actually introduced this backwards-incompatible change in a patch release:

https://community.magento.com/t5/Magento-DevBlog/Backward-incompatible-Changes-in-the-Mail-Library-for-Magento-2/ba-p/144787

We'll have to add some more type checking to work around this...

**Comment by flowmailer-richard** [comment]
We will investigate this further, but please be advised there's a patch available at:
https://magento.com/tech-resources/download#download2333

They state these changes will be included in Magento 2.3.4, but also that plugin developers should expect incompatibility with 2.3.4 (not yet released).

**Comment by timxsarus** [comment]
@flowmailer-richard Thanks, we have applied the patch that changes some of the code back. However the patch itself seems to be incomplete since `\Magento\Framework\Mail\Template\TransportBuilder::prepareMessage` would still populate `$this->message` with a `\Magento\Framework\Mail\EmailMessageInterface` object. I've added a custom patch to correct this which I'll post here in case someone else runs into this: https://gist.github.com/timxsarus/468cdbb1a66759e4a0f297f9e7ffe21e

**Comment by flowmailer-richard** [comment]
Please note there's now also a Patch 2.3.2.2 containing all security patches from 2.3.3 but without the interface changes. This buys us some time to figure out how to handle this.

**Comment by flowmailer-richard** [comment]
We will be pushing a new version of the connector to Github in a few minutes. Please note we reworked the structure to better fit the Magento 2.3.3+ codebase and make it less likely to break in the future.

This commit passed preliminary internal testing, but hasn't been tested in the field yet. Since the time pressure on this fix we wanted to share the code asap, so you can participate in the testing before we tag it for release.

Please feel free to check it out!

**Comment by flowmailer-richard** [comment]
Fixed, if you're using M2.3.3, please update to r1.0.10!
